#Developers name
developer.name=Gboluwaga
developer.stack=Java
age =40
# HTTP SERVER PORT
server.port =7070
#CONTENTENT PATH OF THE APPLICATION
server.servlet.context-path=/api/ifraud


# SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# APPLICATION INFORMATION
spring.application.name=Ifraud

# DATABASE INFORMATION
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


#DOCKER
spring.datasource.url=jdbc:postgresql://localhost:5000/fraud
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update



##H2 DATABASE
#spring.h2.console.path =/h2-console
#spring.datasource.driver-class-name =org.h2.Driver
#spring.jpa.database-platform =org.hibernate.dialect.H2Dialect
## Enable H2 Console
#spring.h2.console.enabled=true
##server.port=7070
#spring.sql.init.mode=always
#spring.datasource.url =jdbc:h2:mem:testdb
#spring.datasource.username =admin_viewer
#spring.datasource.password =password
##spring.jpa.hibernate.ddl-auto=update
##spring.sql.init.mode=always


//spring.datasource.hikari.maximum-pool
spring.datasource.hikari.maximum-pool-size=3
//Logging
logging.level.org.springframework.security=DEBUG


# HIBERNATE ORM CONFIGURATION

spring.jpa.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SECURITY
spring.security.user.name=admin
spring.security.user.password=topSecrete
#management.endpoints.web.exposure.exclude=beans,mappings
management.endpoints.web.exposure.exclude=*

#Excluded properties
management.info.env.enabled=true
info.app.name="Ifraud App
info.app.description="App built by the grace of Elroi"

info.app.version="1.0.0"
#Turn off Spring banner
spring.main.banner-mode =off

#Reduce logging level, St logging level to warn
logging.level.root =warn

