#Developers name
developer.name=Gboluwaga
developer.stack=Java
age =40
# HTTP SERVER PORT
server.port =7070
#CONTENTENT PATH OF THE APPLICATION
server.servlet.context-path=/api/ifraud

# APPLICATION INFORMATION
spring.application.name=Ifraud

# DATABASE INFORMATION
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.open-in-view=false

//Logging
logging.level.org.springframework.security=DEBUG


# HIBERNATE ORM CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SECURITY
spring.security.user.name=admin
spring.security.user.password=topSecrete
#management.endpoints.web.exposure.exclude=beans,mappings
management.endpoints.web.exposure.exclude=*

#Excluded properties
management.info.env.enabled=true
info.app.name="Ifraud App
info.app.description="App built by the grace of Elroi"

info.app.version="1.0.0"
#Turn off Spring banner
spring.main.banner-mode =off

#Reduce logging level, St logging level to warn
logging.level.root =warn
